name: First Workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: RRR
        run: |
          echo Naatu Naatu
          echo Oscar 
      - name: Print goodbye
        run: echo "Done-bye"
      
